# Generated by Django 4.2.30 on 2026-04-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RSVPResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.CharField(choices=[('coming', 'Я приду / Мы придем'), ('not_coming', 'Прийти не получится'), ('plus_one', 'Буду +1')], max_length=20)),
                ('full_name', models.CharField(max_length=255)),
                ('drinks', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
